### ISSUE TITLE
Disabled menu on Mac

### ISSUE THREAD

**Issue by greg-ms** [pydio/pydio-sync-ui#13]
On OS X 10.10 most of the tray menu is disabled and no assistant or something else appears. Even "About" doesn't show any modal, only "Quit" works. 
Got the problem already at first install.

![pydio](https://cloud.githubusercontent.com/assets/10226178/5973321/36d99d66-a867-11e4-9567-2398da001a75.png)

**Comment by cdujeu** [comment]
Hi Greg, 
This state means that the agent is not started. 
Please use the forum (there is a dedicated PydioSync Issues forum) and we'll add a bug here only once it will be correctly qualified.
Charles

**Comment by cdujeu** [comment]
https://pyd.io/f/

**Comment by greg-ms** [comment]
Thank you for the fast reply! I've created a Post in your Forum.
