### ISSUE TITLE
multi-monitor gui not on screen

### ISSUE THREAD

**Issue by 2020media** [pydio/pydio-sync-ui#21]
I’ve got an issue to report.
Main window or about window or whatever window is always trying to appear too far on the left or right. So it’s always hidden. It’s visible in taskbar and you can move it back to the desktop using hot-keys, but once you close it and try to open again it’s behind the edge of the desktop again. It’s really annoying to get this window back over and over.
Using: Win7 x64

You can actually see it happening as the animation that plays when you reopen the gui, the expanding settings just zips off the side of the screen.

I have two monitors and I saw a similar post to this in the forum so I'm /assuming/ it's a multi-monitor related problem.

**Comment by plexorama** [comment]
I had the same issue with to monitors. The following patch should fix the issue:

diff --git a/src/systray/window.cpp b/src/systray/window.cpp
index 9b7689b..f593468 100755
--- a/src/systray/window.cpp
+++ b/src/systray/window.cpp
@@ -139,8 +139,9 @@ void Window::show()
     // link the javascript dialog of the ui to the system FileDialog
     settingsWebView->page()->currentFrame()->addToJavaScriptWindowObject("PydioQtFileDialog", j
-    int desktopHeight = QApplication::desktop()->height();
-    int desktopWidth = QApplication::desktop()->width();
+    QRect rec = QApplication::desktop()->screenGeometry();
+    int desktopHeight = rec.height();
+    int desktopWidth = rec.width();
     int tray_x = this->tray->geometry().center().x();

     if(desktopHeight < 800){

**Comment by intensite** [comment]
Hello, will this patch be soon pushed to master as the application is unusable as it is.  I have dual monitor setup and after the initial installation, it is impossible to bring the settings dialog in the viewport.

Do you have a workaround?

**Comment by cdujeu** [comment]
hi guys, sorry this was not integrated yet. We'll do our best to have this integrated and keep you posted when you can get it from our dev builds.

**Comment by sagaru** [comment]
Integrated in the latest commit.

https://github.com/pydio/pydio-sync-ui/commit/a4614293e0d712904b807f51c1c336ae1c093152
