### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by aacebedo** [pydio/pydio-sync-ui#25]
Hi! 
I'm facing an authentication failure when using latest pydio-agent (built using the github page instructions) with latest tgz release of pydio ui. 
I'm starting  the agent on Ubuntu 15.04 without any problem. It generates a user/password pair in the config.  When starting,  pydio-ui informs me of an authentication error when trying to connect to the agent. I didn't found any parameter to change the login or password it uses. 

Can you tell me what I'm missing?

**Comment by sagaru** [comment]
Hello,
Make use of the forum to post your questions and to get proper instructions, and only once a bug is "qualified", you can post on github. Thanks.

Forum: https://pyd.io/f/
