### ISSUE TITLE
Pydio Unity indicator

### ISSUE THREAD

**Issue by Natim** [pydio/pydio-sync-ui#27]
Running Pydio with Unity makes it on top left of the screen on top of all applications everything
![bug-pydio](https://cloud.githubusercontent.com/assets/229453/10975625/2d050bd8-83e8-11e5-9849-e4139f1730ce.png)

Is there a way to put it in the tray or shall I try to make it a unity compatible indicator?

**Comment by cdujeu** [comment]
Hi Natim
it's a known issue that we did not really tackle yet. If you want to find the right solution, we would be happy!

**Comment by 7omate** [comment]
Updating this library should do the trick https://launchpad.net/sni-qt

**Comment by 7omate** [comment]
Updated Qt PydioSync 1.2.7 (64 bits) works
